### ISSUE TITLE
Error importing json data in Ghidra

### ISSUE THREAD

**Issue by Daniels118** [openblack/bw1-decomp#2]
When I run the following command from the Ghidra Python console:

    __import__("imp").load_source('analysis', r'xxxxx/extracted_reversing_data_bw_141.json').main(currentProgram, state)

I get the following error:

    Traceback (most recent call last):
      File "python", line 1, in <module>
    
    Please provide a CPython 2.7 bytecode file (.pyc), e.g. run
        python -m py_compile xxxxx/extracted_reversing_data_bw_141.json
    
    Alternatively, specify a CPython 2.7 command via the python.cpython2 property, e.g.:
        jython -Dpython.cpython2=python
    or (e.g. for pip) through the environment variable JYTHON_OPTS:
        export JYTHON_OPTS="-Dpython.cpython2=python"
    
    	at org.python.compiler.Module.loadPyBytecode(Module.java:837)
    	at org.python.compiler.Module.compile(Module.java:1001)
    	at org.python.core.imp.compileSource(imp.java:549)
    	at org.python.core.imp.createFromSource(imp.java:577)
    	at org.python.core.imp.createFromSource(imp.java:562)
    	at org.python.modules._imp.load_source(_imp.java:161)
    	at org.python.modules._imp.load_source(_imp.java:146)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    
    java.lang.RuntimeException: java.lang.RuntimeException: Module or method too large in `xxxxx/extracted_reversing_data_bw_141.json`.
    
    Please provide a CPython 2.7 bytecode file (.pyc), e.g. run
        python -m py_compile D:/Archivio/Giochi/Black_and_White/extracted_reversing_data_bw_141.json
    
    Alternatively, specify a CPython 2.7 command via the python.cpython2 property, e.g.:
        jython -Dpython.cpython2=python
    or (e.g. for pip) through the environment variable JYTHON_OPTS:
        export JYTHON_OPTS="-Dpython.cpython2=python"

I've tried to set Python 2.7 as suggested by executing these 2 lines:

    from java.lang import System
    System.setProperty('python.cpython2', 'E:/Python27/python.exe')

then the command has produced a file named `extracted_reversing_data_bw_141.jsonc` but it still failed with the following error:

    Traceback (most recent call last):
      File "python", line 1, in <module>
    AttributeError: 'module' object has no attribute 'main'

which sounds fair (why compiling data should solve the problem, if the problem is in the code?)

Am I missing something?

**Comment by bwrsandman** [comment]
Can you post the about info for your runblack.
![image](https://github.com/user-attachments/assets/0f56a46c-1fef-4499-b2f7-19d244bf359d)

**Comment by Daniels118** [comment]
![image](https://github.com/user-attachments/assets/2d34fa53-e33e-4e63-a57e-cf9ed9e58ea6)
